### PR TITLE
Issue 10

### LINKED ISSUE #10: Upload auth object to UserDataManager instead of userID
We should be using an auth object (rather than a userid string) in the driver constructors and retrieving userid and access tokens directly from it.

### PR DESCRIPTION
**Pull request by balmas**
required for alpheios-project/components#355
requires alpheios-project/data-models#76

- fixes #10 - uses auth credentials from user data manger 
- adds getWordListItemCount method to WordListController to get the count of all items across all lists
- reduces the number of queries executed when updating the remote database to only query for existing items first if the update includes the context data which needs to be merged
- changes WordlistController.initLists to replay any in memory data wordlist actions if initializing with a user data manager, and otherwise to clear the wordlists. This allows for users to login and logout on a workstation, operating with in-memory lists only when not logged in and to add words they looked up while not logged in once they login

I think there is still more to do here including:
- reading the mock user access token from the protected config repo rather than embedding it in the package.json environment variables (need to investigate how best to handle this for travis)
- I think we might have to impose a limit on the size of the in-memory wordlists - both for non-logged in sessions and to allow for what is held in memory to only be a subset of what is stored for logged-in sessions.

But I think what we have with these changes will allow Monica to begin testing this feature

### CODE REVIEW

**Review by kirlat — APPROVED** [review]
Looks good to me, but I'm not very familiar with the wordlist logic and might miss something

**Comment by irina060981** [comment]
@balmas , as I see you changed the logic of initializing and merging a little, I tried to upload all your branches to embed-lib and see myself how it works now between two browsers.
First I tried to do it with a standard auth workflow, but I couldn't, may be I am doing something wrong:

1) I uploaded all dev branches to `embed-lib`
2) I updated auth with `auth0-env-dev-update` (successfully)
3) I have loaded `http://localhost:8888/demo/auth.html`
4) I have logged in and I see this in the tab:
image

And after that `WordListController.initLists` method is failed with the following errors:
image

The authorization is failed.
I looked at the request that was made in the Network tab and see that there is some problems with accessToken inside header:

image

**Comment by irina060981** [comment]
2. Then I tried to check it without login - if I tried to load simple http://localhost:8888/demo/
    It is not working at all - I couldn't select any word. There were the following errors:
image

**Comment by irina060981** [comment]
3. The last I tried to check it with http://localhost:8888/demo/auth.html
    but without login
    Here it worked - I could select any word and it is placed in the list but not saved anywhere.
    I tried to select the same word on the same page (without reload) and it merges data properly.

   Am I right and you decide not to store any data to IndexedDB if the user is not logged in?
   So all wordlists with all hoonym data are stored only in the memory and it is increased everytime the new word is selected? 
I thought we were discussing to store all data (for even not logged in users) in IndexedDB and upload data details (homonym, lemma translation, may be word usage in the future) on a word selected. And in memory we store only short list that is shown inside the tab? 

I would be happy if you will help me to test the data with remote source too :)

**Comment by balmas** [comment]
I have to confess, I didn't test it in the embed-lib, so I will do that and make sure it is working and let you know if I figure out what is going wrong for you.  Yes, it's correct that I am not currently storing to the local indexed db unless the user is logged in,  using in-memory storage for the non-logged in case instead.  I originally wanted to use indexed db for that, and we still could, but as I started to implement the connection with auth, some complexities occurred to me with the scenario of a shared workstation. We would probably need to allow users to clear the local history and if they didn't then if they do login, they could end up with other peoples words in their lists.  For the moment the simplest seems to avoid that scenario but I think it's important that we have the ability to do this if we want to.

**Comment by balmas** [comment]
@irina060981 I think this is working now with alpheios-project/embed-lib#42. Let me know if you find otherwise.

**Pull request merged**
