### PR TITLE
Added support for separate definitions ready events

### PR DESCRIPTION
**Pull request by kirlat**
Updated to support separate definitions availability events within the LexicalQuery. This is a companion request for alpheios-project/comonents#756.

### CODE REVIEW

**Comment by kirlat** [comment]
I'm not fully familiar with the wordlist tests, but it seems some network based tests are failing at random probably due to remote server availability or connectivity. One test fails because of the 1 sec. difference in a created time due to a network delay. Not sure if we can do anything about it. 

I think the tests itself are most likely OK because they are related to the part not affected by the changes in this PR; changes introduced here are very minimal.

**Review by balmas — APPROVED** [review]
looks ok to me

**Review by irina060981 — APPROVED** [review]
Looks ok for me

**Comment by irina060981** [comment]
> I'm not fully familiar with the wordlist tests, but it seems some network based tests are failing at random probably due to remote server availability or connectivity. One test fails because of the 1 sec. difference in a created time due to a network delay. Not sure if we can do anything about it.
> 
> I think the tests itself are most likely OK because they are related to the part not affected by the changes in this PR; changes introduced here are very minimal.

@kirlat, don't worry! it is really easy to fix it (I fixed it).
The problem is only in the parallel execution of two instances here. And they makes conflict.
I simply rebuild such Travis task one by one - and all tests are passed well.

**Comment by kirlat** [comment]
> @kirlat, don't worry! it is really easy to fix it (I fixed it).
> The problem is only in the parallel execution of two instances here. And they makes conflict.
> I simply rebuild such Travis task one by one - and all tests are passed well.

Great, thank you very much, @irina060981 !

**Pull request merged**
